[project]
name = "informatics"
version = "0.0.1"
license = {file = "LICENSE"}
description = "basic algorithm toolkit"
readme = "README.rst"
authors = [
    { name="ChenZHANG", email="chen.zhang_06sept@foxmail.com" },
  ]
maintainers = [
    {name = "ChenZHANG", email = "chen.zhang_06sept@foxmail.com"},
]
requires-python = ">=3.9"
dependencies = [
    'numpy'
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Healthcare Industry',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Information Analysis',
    'License :: OSI Approved :: Apache Software License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]


[project.optional-dependencies]
doc = ['sphinx']

[project.urls]
source = 'https://github.com/CubicZebra/informatics'

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "cython"]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]  # ["."] by default
include = ["src*"]
namespaces = false  # true by default
